"""initial migration

Revision ID: 7cc7e6057fdf
Revises: 
Create Date: 2025-04-03 23:26:19.121408

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '7cc7e6057fdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
